# Generated by Django 4.0.6 on 2022-10-05 23:25

import Mensajeria.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaMensaje', models.CharField(default='2022/10/05', max_length=50)),
                ('horaMensaje', models.CharField(default=Mensajeria.models.get_default_my_hour, max_length=50)),
                ('usuarioOrigen', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
                ('usuarioDestino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
