# Generated by Django 4.0.6 on 2022-10-07 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='fechaMensaje',
            field=models.CharField(default='07/10/2022', max_length=50),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='usuarioDestino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioDestino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='usuarioOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioOrigen', to=settings.AUTH_USER_MODEL),
        ),
    ]
