# Generated by Django 4.0.6 on 2022-10-09 20:23

import Mensajeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0002_alter_mensajeria_fechamensaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaMensajeContacto', models.CharField(default='09/10/2022', max_length=50)),
                ('horaMensajeContacto', models.CharField(default=Mensajeria.models.get_default_my_hour, max_length=50)),
                ('mensajeContacto', models.CharField(max_length=500)),
                ('telefonoContacto', models.IntegerField()),
                ('nombreContacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='fechaMensaje',
            field=models.CharField(default='09/10/2022', max_length=50),
        ),
    ]
