# Generated by Django 4.0.6 on 2022-10-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0003_contacto_alter_mensajeria_fechamensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
