# Generated by Django 4.0.6 on 2022-10-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0004_delete_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='fechaMensaje',
            field=models.CharField(default='10/10/2022', max_length=50),
        ),
    ]
