# Generated by Django 4.0.6 on 2022-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosmascota',
            name='especieMascota',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fechaConsulta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='pesoMascota',
            field=models.FloatField(),
        ),
    ]
