# Generated by Django 4.0.6 on 2022-09-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosmascota',
            name='nombrePropietarioMascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppVet.datospropietario'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='nombreMascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppVet.datosmascota'),
        ),
    ]
