# Generated by Django 4.0.6 on 2022-09-22 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0004_datosmascota_nombrepropietariomascota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosmascota',
            name='nombrePropietarioMascota',
        ),
        migrations.AddField(
            model_name='datosmascota',
            name='apellidoPropietarioMascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppVet.datospropietario'),
        ),
        migrations.DeleteModel(
            name='historiaClinica',
        ),
    ]
