# Generated by Django 4.0.6 on 2022-09-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0005_remove_datosmascota_nombrepropietariomascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosmascota',
            name='apellidoPropietarioMascota',
            field=models.CharField(max_length=30),
        ),
    ]
