# Generated by Django 4.0.6 on 2022-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0009_alter_datosmascota_apellidopropietariomascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosmascota',
            name='apellidoPropietarioMascota',
            field=models.CharField(max_length=30),
        ),
    ]
