# Generated by Django 4.0.6 on 2022-09-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0010_alter_datosmascota_apellidopropietariomascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosmascota',
            name='apellidoPropietarioMascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppVet.datospropietario'),
        ),
    ]
