# Generated by Django 4.0.6 on 2022-10-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0017_datosmascota_imagenmascota_delete_imagenmascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosmascota',
            name='imagenMascota',
        ),
    ]
