# Generated by Django 4.0.6 on 2022-10-10 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0018_remove_datosmascota_imagenmascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='motivoConsulta',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
