# Generated by Django 4.0.6 on 2022-10-10 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0019_alter_historiaclinica_motivoconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnosticoMascota',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
